name: Build and Deploy

on:
  workflow_run:
    workflows: ["Build and Deploy Image"]
    branches: [master]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
