name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Test"]
    branches: [ master ]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
